export const actionTypes = {
    GET_POPULAR_MOVIES_LIST :"GET_POPULAR_MOVIES_LIST",
    UPDATE_POPULAR_MOVIES_LIST :"UPDATE_POPULAR_MOVIES_LIST",

    GET_SEARCH_MOVIES_LIST:"GET_SEARCH_MOVIES_LIST",
    UPDATE_SEARCH_MOVIES_LIST:"UPDATE_SEARCH_MOVIES_LIST",

    
}